CREATE TABLE IF NOT EXISTS user_profiles (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT NOT NULL UNIQUE,
    full_name VARCHAR(191) NULL,
    position VARCHAR(191) NULL,
    email VARCHAR(191) NULL,
    wa_number VARCHAR(50) NULL,
    linkedin VARCHAR(191) NULL,
    github VARCHAR(191) NULL,
    city VARCHAR(191) NULL,
    about_me TEXT NULL,
    image LONGTEXT NULL,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_user_profiles_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
