CREATE TABLE IF NOT EXISTS work_histories (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT NOT NULL,
    company_name VARCHAR(191) NULL,
    position VARCHAR(191) NULL,
    start_date DATE NULL,
    end_date DATE NULL,
    created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_work_histories_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS work_history_points (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    work_history_id BIGINT NOT NULL,
    point TEXT NULL,
    created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_work_history_points_work_history FOREIGN KEY (work_history_id) REFERENCES work_histories(id) ON DELETE CASCADE
);
